name: 'COMPEON Deploy'
description: 'Greet someone and record the time'
inputs:
  bucket:
    description: 'Name of the S3 bucket'
    required: true
  source:
    description: 'Path to the code to be deployed'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: false
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: false
  aws-default-region:
    description: 'AWS Default Region'
    required: false
runs:
  using: 'node12'
  main: 'src/main.js'
