name: CI
on: push

env:
  NODE_VERSION: "12"
  NODE_ENV: development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm install
      - run: npm run lint
      - run: npm test
